# Generated by Django 3.2.10 on 2022-03-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
