# Generated by Django 3.2.10 on 2022-03-23 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0003_alter_info_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
