# Generated by Django 3.2.10 on 2022-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220323_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='image',
        ),
        migrations.AddField(
            model_name='info',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
    ]
