# Generated by Django 3.2.10 on 2022-03-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220323_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
