# Generated by Django 3.2.10 on 2022-03-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20220323_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=224)),
                ('description', models.CharField(max_length=225)),
                ('Field', models.CharField(max_length=10)),
            ],
        ),
    ]
