# Generated by Django 3.2.10 on 2022-03-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20220323_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datas',
            new_name='Information',
        ),
    ]
