# Generated by Django 3.2.10 on 2022-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_rename_datas_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Field',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.TextField(max_length=225),
        ),
    ]
