# Generated by Django 3.2.10 on 2022-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20220323_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='targetMarket',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
