# Generated by Django 3.2.10 on 2022-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_information_targetmarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='marketSize',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
