# Generated by Django 3.2.10 on 2022-03-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_information_marketsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='username',
            field=models.CharField(max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
