# Generated by Django 3.2.10 on 2022-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20220324_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='marketSize1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='marketSize2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='marketSize3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.TextField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='field',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(max_length=224, null=True),
        ),
    ]
